Remove invalid Hardhat parameter
When converted to Typescript, error is:

    An unexpected error occurred:

    hardhat.config.ts:58:3 - error TS2322: Type is not assignable to type
    'HardhatUserConfig'.

    Object literal may only specify known properties, and 'loggingEnabled'
    does not exist in type 'HardhatUserConfig'.

    58   loggingEnabled: true,
         ~~~~~~~~~~~~~~~~~~~~